version: 2.1
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: taylorwebk
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: taylorwebk
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  one_and_two:
    jobs:
      -one
      -two
